# For documentation on configuring Supabase locally, see:
# https://supabase.com/docs/guides/local-development

project_id = "zuka"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
